name: Playwright Tests

on:
  push:
    branches: [workflow]
  workflow_dispatch:

env:
  V: 0.0.1

jobs:
  decode_secret_data:
    runs-on: ubuntu-latest
    steps:
      - name: print secret
        run: echo "MY_SECRET=${{ secrets.ENC_JSON }}" >> $GITHUB_ENV
      - name: print
        run: echo  "$MY_SECRET"
      - uses: actions/checkout@v3
      - name: decode file
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ENC_JSON }}" --output ./test.json ./test.json.gpg

      - name: Print test.json file
        run: cat test.json
        continue-on-error: true

      - name: JSON to env
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: 'test.json'
          with: json
          masked: false # !!! set true with secret data !!!

      - name: Print env variables
        run: |
            echo "${{ env.json_REFRESH_TOKEN_USER1 }}"
            echo "${{ env.json_REFRESH_TOKEN_USER2 }}"
            echo "${{ env.json_COMPANY_ID }}"
            
      

  #smoke_tests:
    #runs-on: ubuntu-latest
    #steps:
      #- name: Checkout repository
        #uses: actions/checkout@v3
        #with:
          #ref: ${{ github.event.inputs.branch }}

    

      #- name: Set up Node.js
        #uses: actions/setup-node@v3
        #with:
          #node-version: '23.6.0'

      #- name: Install ci dependency
        #run: npm ci

      #- name: Install browsers
        #run: npx playwright install chromium

      #- name: Run Playwright tests
        #run: npx playwright test tests/example.spec.ts
